language: node_js
node_js: '9'
services: postgresql
before_script: psql -c 'CREATE DATABASE palettepicker;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: UgKrg0jakf07XTvWPeb0Godgqf8TreY3IsUgsxnfmKpFKlBX8s3SRdyaw6tJ/6PpD+DnCOqz9bgdRugNbgGJ+/3cdlMlsMDEnzeAgdBnyhpDYNlpycQD0P5SvohjzxhlPY4E7cLXfy8g8wDLI3JikRUEyT7cN8o8QbaFL7uHGhIy/2eZyk28dvwa17q1Z9Pc1EOir/Z44WFymAg8qgPt05xu1aoUYIk/FFTYxnLpkDdar2a8clQaL4BO/GhBZ4I0Q1Yy9fHzGbirqmg5U/xRCnGoJu6j9sj4/ARkW/EyVS9vC85gsS/YhaiGvzGjR8WfjnB2nAbymFD6UTWJebbDFS3f4Z0fKdpoeDClhnlm8BV/C1WzYDGTg9U78zXvs5r1IHdrVi5b1C4GRW9KCIfxQGF7aDhovQ4SyEDsYcs0sr73uzLD8y2syd1LigGwqVS+ZIK8vbowZcOdJIQTTMEFx4ZJJwxRlTfRTqP8MJ5i6zhJhPTeN/riOo7lFWR2h0IFWv+dLs2VPbCN0P6jrDUTDLhuX3zYBqd2vAhIWfE8HMxXBZPjdUyjsUDHbo8Ya+tgTrwu1BSpPiJhOvNL1tHWT9FHIYo6uJgxzBX453TehvTcHrTX8Q28RNnTwhfHs9N5gzdSfXTEoCJ9E/hndcxvf5oG00bqgB4KjdPmnpwNHJI=
  app: pallettespickers